name: Update Stock Prices

on:
  schedule:
    - cron: "10 21 * * *" # 每天北京时间 5:10 AM 运行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write # 给予写入内容的权限

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install yfinance

      - name: Create data directory if it doesn’t exist
        run: mkdir -p public/data

      - name: Update stock prices
        run: python scripts/update-prices.py

      - name: Commit and push updated prices
        run: |
          git config --global user.name 'wenisy'
          git config --global user.email 'wenisy@gmail.com'
          git add public/data/prices.json

          # 如果有变更则提交
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update stock prices - $(date +'%Y-%m-%d')"
            git push
          fi
