name: Fetch Stock Prices

on:
  schedule:
    - cron: "10 21 * * *"  # 每天北京时间 5:10 AM 运行
  workflow_dispatch:     # 允许手动触发

jobs:
  fetch-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Create data directory if it doesn't exist
        run: mkdir -p public/data
        
      - name: Fetch stock prices
        run: node scripts/fetchPrices.js
        
      - name: Commit and push updated prices
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add public/data/prices.json
          
          # 如果有变更则提交
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update stock prices - $(date +'%Y-%m-%d')"
            git push
          fi